### ISSUE TITLE
Can't build on Alma Linux 9.4

### ISSUE THREAD

**Issue by gaedeb** [abbbi/nullfsvfs#25]
I have already opened a ticket to Alma Support.

I can't build the module because of this error:

```
make -C /lib/modules/5.14.0-427.13.1.el9_4.x86_64/build M=/home/toto/nullfsvfs-master modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-427.13.1.el9_4.x86_64'
  CC [M]  /home/toto/nullfsvfs-master/nullfs.o
/home/toto/nullfsvfs-master/nullfs.c: In function ‘nullfs_tmpfile’:
/home/toto/nullfsvfs-master/nullfs.c:560:15: error: passing argument 1 of ‘d_tmpfile’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  560 |     d_tmpfile(dentry, inode);
      |               ^~~~~~
      |               |
      |               struct dentry *
In file included from ./include/linux/fs.h:8,
                 from ./include/linux/seq_file.h:12,
                 from /home/toto/nullfsvfs-master/nullfs.c:30:
./include/linux/dcache.h:254:23: note: expected ‘struct file *’ but argument is of type ‘struct dentry *’
  254 | extern void d_tmpfile(struct file *, struct inode *);
      |                       ^~~~~~~~~~~~~
/home/toto/nullfsvfs-master/nullfs.c: At top level:
/home/toto/nullfsvfs-master/nullfs.c:581:19: error: initialization of ‘int (*)(struct user_namespace *, struct inode *, struct file *, umode_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct file *, short unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int)’} [-Werror=incompatible-pointer-types]
  581 |     .tmpfile    = nullfs_tmpfile,
      |                   ^~~~~~~~~~~~~~
/home/toto/nullfsvfs-master/nullfs.c:581:19: note: (near initialization for ‘nullfs_dir_inode_operations.tmpfile’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:299: /home/toto/nullfsvfs-master/nullfs.o] Error 1
make[1]: *** [Makefile:1934: /home/toto/nullfsvfs-master] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-427.13.1.el9_4.x86_64'
make: *** [Makefile:5: ko] Error 2
```

Kernel version is < 6.1.0:
5.14.0-427.13.1.el9_4.x86_64

still in the kernel header as long as I could see, the declaration of d_tmpfile is:
extern void d_tmpfile(struct file *, struct inode *);

hence the issue building the module.

Any idea?

Thanks!

**Comment by abbbi** [comment]
try adjusting this ifdef.
maybe alma linux has backported some changes from higher linux kernel version to 5.14??

```
  #if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 0) 
      d_tmpfile(file, inode);
  #else
      d_tmpfile(dentry, inode);                     
  #endif 
```

**Comment by gaedeb** [comment]
Thank you Michael!

I do not think the problem is with nullfs. 
https://github.com/torvalds/linux/blob/v5.14/include/linux/dcache.h

dentry is what I am expecting using a kernel 5.14.0

I will come back as soon as someone from Alma Community will reply to my question.

I could build the kernel module modifying in the right place the dentry with file.

Thanks again!

**Comment by abbbi** [comment]
I guess the kernel in Alma has some patches from newer Kernels backportet.. looking at the Alma kernel source Package should bring some insights

**Comment by scaronni** [comment]
Patches that fixes building on EL 9 (and clones): https://github.com/negativo17/kmod-nullfs/blob/master/nullfs-el9.patch
