### ISSUE TITLE
Failing to build with kernel 6.5.2

### ISSUE THREAD

**Issue by bruno-at-bareos** [abbbi/nullfsvfs#20]
Hello, I'm trying to get this build on openSUSE Tumbleweed which has all the newest software stack in :-)
unfortunately the make simply failed with kernl 6.5.2

```make
make -C /lib/modules/6.5.2-1-default/build M=/git/nullfsvfs modules
make[1]: Entering directory '/usr/src/linux-6.5.2-1-obj/x86_64/default'
  CC [M]  /git/nullfsvfs/nullfs.o
/git/nullfsvfs/nullfs.c:60:6: error: ‘posix_acl_access_xattr_handler’ undeclared here (not in a function); did you mean ‘posix_acl_xattr_header’?
   60 |     &posix_acl_access_xattr_handler,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      posix_acl_xattr_header
/git/nullfsvfs/nullfs.c:61:6: error: ‘posix_acl_default_xattr_handler’ undeclared here (not in a function); did you mean ‘posix_acl_xattr_header’?
   61 |     &posix_acl_default_xattr_handler,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |      posix_acl_xattr_header
make[3]: *** [/usr/src/linux-6.5.2-1/scripts/Makefile.build:244: /git/nullfsvfs/nullfs.o] Error 1
make[2]: *** [/usr/src/linux-6.5.2-1/Makefile:2049: /git/nullfsvfs] Error 2
make[1]: *** [../../../linux-6.5.2-1/Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-6.5.2-1-obj/x86_64/default'
make: *** [Makefile:5: ko] Error 2
```

Maybe you have some ideas about how to fix that.
(of course beside the kernel development, I also have the following installed
libacl-devel-2.3.1-2.11
libattr-devel-2.5.1-1.27

**Comment by abbbi** [comment]
can you check the commit from this pull request just created:

 https://github.com/abbbi/nullfsvfs/pull/21

it should fix the build, but i have not checked functionality ..

**Comment by abbbi** [comment]
seems to work for me:

```
localhost:/home/vagrant/nullfsvfs # uname -a
Linux localhost 6.5.2-1-default #1 SMP PREEMPT_DYNAMIC Fri Sep  8 07:32:27 UTC 2023 (fdde566) x86_64 x86_64 x86_64 GNU/Linux
localhost:/home/vagrant/nullfsvfs # setfacl -m d:u:root:r /sinkhole/acl/
localhost:/home/vagrant/nullfsvfs # getfacl /sinkhole/acl/
getfacl: Removing leading '/' from absolute path names
# file: sinkhole/acl/
# owner: root
# group: root
user::rwx
group::rwx
other::rwx

```

**Comment by bruno-at-bareos** [comment]
You were so quick I wasn't able to thank you before closing :-) and installed
Will try to use and understand why one of our program failed. in the attribute restore.

```

**Comment by abbbi** [comment]
np, plz note nullfs does not have xattr support (only regular facl)
