### ISSUE TITLE
fails to build on alma 8.10 (4.18): finish_open_simple

### ISSUE THREAD

**Issue by themoonisacheese** [abbbi/nullfsvfs#29]
when attempting to build and use on alma 8.10, the following error is displayed:

```
[root@onyx nullfsvfs]#   make -C /lib/modules/$(uname -r)/build M=$PWD modules_install INSTALL_MOD_DIR=kernel/fs/nullfs
make : on entre dans le répertoire « /usr/src/kernels/4.18.0-553.54.1.el8_10.x86_64 »
  DEPMOD  4.18.0-553.54.1.el8_10.x86_64
make : on quitte le répertoire « /usr/src/kernels/4.18.0-553.54.1.el8_10.x86_64 »
[root@onyx nullfsvfs]# depmod
[root@onyx nullfsvfs]# modprobe nullfs
modprobe: FATAL: Module nullfs not found in directory /lib/modules/4.18.0-553.54.1.el8_10.x86_64
```
the directory in question is created, but nothing is written to it:
```
[root@onyx fs]# ls /lib/modules/4.18.0-553.54.1.el8_10.x86_64/kernel/fs/nullfs/ -la
total 4
drwxr-xr-x  2 root root    6 10 juin  17:09 .
drwxr-xr-x 26 root root 4096 10 juin  17:09 ..
```

simply using the `make` command (still as root) instead of the command in the readme fails with:
```
[root@onyx nullfsvfs-0.18]# make
make -C /lib/modules/4.18.0-553.54.1.el8_10.x86_64/build M=/tmp/nullfsvfs-0.18 modules
make[1] : on entre dans le répertoire « /usr/src/kernels/4.18.0-553.54.1.el8_10.x86_64 »
  CC [M]  /tmp/nullfsvfs-0.18/nullfs.o
/tmp/nullfsvfs-0.18/nullfs.c: Dans la fonction « nullfs_tmpfile »:
/tmp/nullfsvfs-0.18/nullfs.c:576:12: error: déclaration implicite de la fonction « finish_open_simple »; vouliez-vous utiliser « single_open_size » ? [-Werror=implicit-function-declaration]
     return finish_open_simple(file, 0);
            ^~~~~~~~~~~~~~~~~~
            single_open_size
/tmp/nullfsvfs-0.18/nullfs.c:576:31: error: « file » non déclaré (première utilisation dans cette fonction)
     return finish_open_simple(file, 0);
                               ^~~~
/tmp/nullfsvfs-0.18/nullfs.c:576:31: note: chaque identificateur non déclaré est rapporté une seule fois pour chaque fonction dans laquelle il apparaît
/tmp/nullfsvfs-0.18/nullfs.c:577:1: warning: le contrôle a atteint la fin d'une fonction non « void » [-Wreturn-type]
 }
 ^
cc1 : certains avertissements sont traités comme des erreurs
make[2]: *** [scripts/Makefile.build:324: /tmp/nullfsvfs-0.18/nullfs.o] Error 1
make[1]: *** [Makefile:1619: _module_/tmp/nullfsvfs-0.18] Error 2
make[1] : on quitte le répertoire « /usr/src/kernels/4.18.0-553.54.1.el8_10.x86_64 »
make: *** [Makefile:5: ko] Error 2
```

**Comment by abbbi** [comment]
see issue #25

it appears alma linux may ship an patched kernel that is incompatible with the stock 4.18 kernel headers, thus the module fails to build because function declarations dont match:

```
/tmp/nullfsvfs-0.18/nullfs.c:576:12: error: déclaration implicite de la fonction « finish_open_simple »; vouliez-vous utiliser « single_open_size » ? [-Werror=implicit-function-declaration]
     return finish_open_simple(file, 0);
```

you have to install kernel headers and check the definitions and adjust the module code.

It may also be that noone has yet used this module with kernel version 4.18, and i didnt test either.

**Comment by themoonisacheese** [comment]
that did it, thanks.

**Comment by abbbi** [comment]
thanks, pushed a fix that should solve this problem.
