### ISSUE TITLE
Won't make on a Centos 7.8 system

### ISSUE THREAD

**Issue by preese** [abbbi/nullfsvfs#1]
I'm sure its a simple library or something but...

I also wouldn't blame you if you want to leave this old version in the dust, it does work fine on Centos8 and Fedora32.

Thanks!

make -C /lib/modules/3.10.0-1127.18.2.el7.x86_64/build M=/home/preese/nullfsvfs modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-1127.18.2.el7.x86_64'
  CC [M]  /home/preese/nullfsvfs/nullfs.o
/home/preese/nullfsvfs/nullfs.c:116:5: error: unknown field ‘read_iter’ specified in initializer
     .read_iter  = generic_file_read_iter,
     ^
/home/preese/nullfsvfs/nullfs.c:116:19: error: ‘generic_file_read_iter’ undeclared here (not in a function)
     .read_iter  = generic_file_read_iter,
                   ^
/home/preese/nullfsvfs/nullfs.c:117:5: error: unknown field ‘write_iter’ specified in initializer
     .write_iter = generic_file_write_iter,
     ^
/home/preese/nullfsvfs/nullfs.c:117:19: error: ‘generic_file_write_iter’ undeclared here (not in a function)
     .write_iter = generic_file_write_iter,
                   ^
/home/preese/nullfsvfs/nullfs.c: In function ‘nullfs_get_inode’:
/home/preese/nullfsvfs/nullfs.c:230:13: error: implicit declaration of function ‘inode_nohighmem’ [-Werror=implicit-function-declaration]
             inode_nohighmem(inode);
             ^
cc1: some warnings being treated as errors
make[2]: *** [/home/preese/nullfsvfs/nullfs.o] Error 1
make[1]: *** [_module_/home/preese/nullfsvfs] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-1127.18.2.el7.x86_64'
make: *** [ko] Error 2

**Comment by abbbi** [comment]
seems  kernel 3.10 that comes with centos 7.8 does not yet support the functions. They have been added with version 3.15:

 https://github.com/torvalds/linux/commit/293bc98

**Comment by preese** [comment]
Thanks for your reply.  I thought it might be the OS version too.  Just waiting for an update of the application to a more modern OS version.  Seems like a great tool to have available when needed.  The fact it is faster than the fuse based one is a big win!    Appreciate your time in taking a look.

**Comment by abbbi** [comment]
hi,

can you check out the version from centos7 branch.

https://github.com/abbbi/nullfsvfs/tree/centos7

it should work with the kernel version shipped with centos7

**Comment by preese** [comment]
WOW!! yup works on Centos7.8!!!!  Works very similarly to how it runs on Centos8 and Fedora32.

Still seems pretty fast too.  Magic fingers of yours.

Also found this little script line to be very cool and I'll be using it often!
cat /dev/zero | pv > /sinkhole/testdir/myfile

**Comment by abbbi** [comment]
thanks, merged the changes to master
